version: '2'

services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      # Expose https port
      - "443:443"
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
      # Mount certs folder
      - ./certs:/etc/nginx/certs
    links:
      - php

  php:
    build: 
      context: ./dockerfiles/php/
      dockerfile: ./Dockerfile
    volumes:
        - ./code:/code
    links:
      - db

  db:
    # Created build context, and removed image: 
    build:
      context: ./dockerfiles/postgres/
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./schema.sql:/schema.sql
      - ./data.sql:/data.sql
    environment:
      POSTGRES_PASSWORD: assignment1dbadmin

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

